default_language_version:
  node: system

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=15000"]
      - id: check-toml
        types: [toml]
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.4.2"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --preview, --unsafe-fixes]

      - id: ruff-format
