# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.11
  - 3.10

install:
  - pip install uv
  - uv sync --group dev

script: uv run pytest

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dolittle007
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: dolittle007/scanitd
    python: 3.10
